name: unit-test

on:
  push:
    branches-ignore:
      - master

jobs:
  unit-test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run test:unit
